[project]
authors = ["Peter Alexander <makeroftools@creativedevelopment.systems>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "website"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build_docs = "mkdocs build"

[dependencies]
max = "*"
python = ">=3.13.5,<3.14"
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.6.14,<10"
pre_commit = ">=4.2.0,<5"
